 const data ={
    productItem:[
        {
            id:1,
            name:'aaaaaaa',
            price:456,
            image:'./img/1.jpg'
        },
        {
            id:2,
            name:'auuuua',
            price:156,
            image:'./img/2.jpg'
        },
        {
            id:3,
            name:'yyyyyaaa',
            price:956,
            image:'./img/3.jpg'
        },
        {
            id:4,
            name:'aeeeea',
            price:5456,
            image:'./img/4.jpg'
        },
        {
            id:5,
            name:'addda',
            price:4356,
            image:'./img/5.jpg'
        },
        {
            id:6,
            name:'abcccca',
            price:4156,
            image:'./img/6.jpg'
        },
        {
            id:7,
            name:'abbb',
            price:4536,
            image:'./img/7.jpg'
        },
        {
            id:8,
            name:'aaaaaaa',
            price:456,
            image:'./img/1.jpg'
        },
        {
            id:29,
            name:'auuuua',
            price:156,
            image:'./img/2.jpg'
        },
        {
            id:31,
            name:'yyyyyaaa',
            price:956,
            image:'./img/3.jpg'
        },
        {
            id:45,
            name:'aeeeea',
            price:5456,
            image:'./img/4.jpg'
        },
        {
            id:57,
            name:'addda',
            price:4356,
            image:'./img/5.jpg'
        },
        {
            id:66,
            name:'abcccca',
            price:4156,
            image:'./img/6.jpg'

        }

    ]
}
export default data;